name: atlas-music-festival

services:
    atlas-music-festival-laravel:
        build:
            context: '.'
            dockerfile: Dockerfile
            # args:
            #     WWWGROUP: '${WWWGROUP}'
        container_name: atlas-music-festival-laravel
        ports:
            - 80:8000
            - 5173:5173
        volumes:
            - '..:/app'
            - 'vendor_cache:/app/vendor'
            - 'node_modules_cache:/app/node_modules'
        command: sh -c "npm install && composer install && composer run dev"
        networks:
            - atlas-music-festival-network

    db:
        image: mysql:8.0
        container_name: atlas-music-festival-db
        environment:
            MYSQL_ROOT_PASSWORD: Password1234*
            MYSQL_USER: atlas_user
            MYSQL_PASSWORD: 1234
            MYSQL_DATABASE: atlas-music-festival_db
        ports:
        - "3306:3306"
        networks:
            - atlas-music-festival-network

networks:
    atlas-music-festival-network:
        driver: bridge

volumes:
    vendor_cache:
    node_modules_cache:
