version: '3'
services:
  atlas-laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Atlas-Music-Festival
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ../:/app
    ports:
      - "8000:8000"
      - "5173:5173"
      - "5174:5174"
    networks:
      - atlas
    depends_on:
      - atlas-db
    entrypoint: ["/app/docker/entrypoint.sh"]
    command: 
      bash -c
        "npm install &&
        composer install &&
        npm run build &&
        php artisan serve --host=0.0.0.0 --port=8000"

  atlas-db:
    image: mysql:8.0
    container_name: atlas_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: atlas
      MYSQL_USER: atlas
      MYSQL_PASSWORD: atlas
      MYSQL_DATABASE: atlas
    ports:
      - "3306:3306"
    networks:
      - atlas

networks:
  atlas:
    driver: bridge